// Generated by scripts/gen-loam-theme.py from docs/design/tokens.json. Do not edit.
import AppKit

/// The Loam design tokens (docs/design). Night is the default theme. Day is the light one.
public enum LoamTheme {
    public struct ColorToken: Sendable, Equatable {
        public let name: String
        public let night: UInt32
        public let day: UInt32
    }

    /// A color that follows the appearance: Night for dark, Day for light.
    public static func dynamic(night: UInt32, day: UInt32) -> NSColor {
        NSColor(name: nil) { appearance in
            let dark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
            return srgb(dark ? night : day)
        }
    }

    public static func srgb(_ hex: UInt32) -> NSColor {
        NSColor(srgbRed: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255,
                blue: CGFloat(hex & 0xFF) / 255, alpha: 1)
    }

    // MARK: Color

    public static let colorTokens: [ColorToken] = [
        ColorToken(name: "bedrock", night: 0x12110f, day: 0xfcfbf8),
        ColorToken(name: "horizon-o", night: 0x1b1916, day: 0xeeeae2),
        ColorToken(name: "horizon-a", night: 0x211e1a, day: 0xf6f3ed),
        ColorToken(name: "horizon-b", night: 0x2a2621, day: 0xffffff),
        ColorToken(name: "rule", night: 0x3a352e, day: 0xd9d2c5),
        ColorToken(name: "frame", night: 0x12110f, day: 0xeeeae2),
        ColorToken(name: "edge", night: 0x7d7567, day: 0x8a8274),
        ColorToken(name: "ink", night: 0xede6da, day: 0x211d18),
        ColorToken(name: "ink-muted", night: 0xaaa192, day: 0x625b4f),
        ColorToken(name: "ink-faint", night: 0x7e7668, day: 0x8a8274),
        ColorToken(name: "moss", night: 0x94c26e, day: 0x3d7526),
        ColorToken(name: "on-moss", night: 0x13200b, day: 0xffffff),
        ColorToken(name: "moss-wash", night: 0x26301e, day: 0xe3eed8),
        ColorToken(name: "needs-you", night: 0xf1b04c, day: 0x94570a),
        ColorToken(name: "needs-you-wash", night: 0x3b2c14, day: 0xfaead0),
        ColorToken(name: "done-unread", night: 0x80b4e6, day: 0x1d5c99),
        ColorToken(name: "done-unread-wash", night: 0x1c2a38, day: 0xdde9f5),
        ColorToken(name: "rust", night: 0xec8a72, day: 0xb0391f),
        ColorToken(name: "rust-wash", night: 0x3a1f18, day: 0xf8e1da),
        ColorToken(name: "focus", night: 0xb6dd8e, day: 0x2d6619),
        ColorToken(name: "selection", night: 0x3d4a2e, day: 0xcfe3bd),
        ColorToken(name: "cursor", night: 0xc9e7a6, day: 0x2d6619),
        ColorToken(name: "ansi-black", night: 0x1b1916, day: 0x2a2520),
        ColorToken(name: "ansi-red", night: 0xe0705a, day: 0xb0391f),
        ColorToken(name: "ansi-green", night: 0x8fbf6a, day: 0x3d7526),
        ColorToken(name: "ansi-yellow", night: 0xe8b65a, day: 0x8a5a00),
        ColorToken(name: "ansi-blue", night: 0x7aa9dc, day: 0x1d5c99),
        ColorToken(name: "ansi-magenta", night: 0xc99ad6, day: 0x8a3f99),
        ColorToken(name: "ansi-cyan", night: 0x74c2b5, day: 0x1d6e66),
        ColorToken(name: "ansi-white", night: 0xcfc7ba, day: 0xd9d2c5),
        ColorToken(name: "ansi-bright-black", night: 0x5a5348, day: 0x6b6458),
        ColorToken(name: "ansi-bright-red", night: 0xf08c76, day: 0xbb4227),
        ColorToken(name: "ansi-bright-green", night: 0xa9d684, day: 0x437f2b),
        ColorToken(name: "ansi-bright-yellow", night: 0xf4cb78, day: 0x8f5f08),
        ColorToken(name: "ansi-bright-blue", night: 0x9cc2ec, day: 0x2f72b3),
        ColorToken(name: "ansi-bright-magenta", night: 0xddb4e6, day: 0xa052ae),
        ColorToken(name: "ansi-bright-cyan", night: 0x95d8cc, day: 0x22766d),
        ColorToken(name: "ansi-bright-white", night: 0xf4eee4, day: 0xfcfbf8),
    ]

    public static let bedrock = surface("bedrock", night: 0x12110f, day: 0xfcfbf8)
    public static let horizonO = surface("horizon-o", night: 0x1b1916, day: 0xeeeae2)
    public static let horizonA = surface("horizon-a", night: 0x211e1a, day: 0xf6f3ed)
    public static let horizonB = surface("horizon-b", night: 0x2a2621, day: 0xffffff)
    public static let rule = surface("rule", night: 0x3a352e, day: 0xd9d2c5)
    public static let frame = surface("frame", night: 0x12110f, day: 0xeeeae2)
    public static let edge = dynamic(night: 0x7d7567, day: 0x8a8274)
    public static let ink = surface("ink", night: 0xede6da, day: 0x211d18)
    public static let inkMuted = surface("ink-muted", night: 0xaaa192, day: 0x625b4f)
    public static let inkFaint = surface("ink-faint", night: 0x7e7668, day: 0x8a8274)
    public static let moss = surface("moss", night: 0x94c26e, day: 0x3d7526)
    public static let onMoss = dynamic(night: 0x13200b, day: 0xffffff)
    public static let mossWash = dynamic(night: 0x26301e, day: 0xe3eed8)
    public static let needsYou = surface("needs-you", night: 0xf1b04c, day: 0x94570a)
    public static let needsYouWash = dynamic(night: 0x3b2c14, day: 0xfaead0)
    public static let doneUnread = surface("done-unread", night: 0x80b4e6, day: 0x1d5c99)
    public static let doneUnreadWash = dynamic(night: 0x1c2a38, day: 0xdde9f5)
    public static let rust = surface("rust", night: 0xec8a72, day: 0xb0391f)
    public static let rustWash = dynamic(night: 0x3a1f18, day: 0xf8e1da)
    public static let focus = dynamic(night: 0xb6dd8e, day: 0x2d6619)
    public static let selection = dynamic(night: 0x3d4a2e, day: 0xcfe3bd)
    public static let cursor = dynamic(night: 0xc9e7a6, day: 0x2d6619)
    public static let ansiBlack = dynamic(night: 0x1b1916, day: 0x2a2520)
    public static let ansiRed = dynamic(night: 0xe0705a, day: 0xb0391f)
    public static let ansiGreen = dynamic(night: 0x8fbf6a, day: 0x3d7526)
    public static let ansiYellow = dynamic(night: 0xe8b65a, day: 0x8a5a00)
    public static let ansiBlue = dynamic(night: 0x7aa9dc, day: 0x1d5c99)
    public static let ansiMagenta = dynamic(night: 0xc99ad6, day: 0x8a3f99)
    public static let ansiCyan = dynamic(night: 0x74c2b5, day: 0x1d6e66)
    public static let ansiWhite = dynamic(night: 0xcfc7ba, day: 0xd9d2c5)
    public static let ansiBrightBlack = dynamic(night: 0x5a5348, day: 0x6b6458)
    public static let ansiBrightRed = dynamic(night: 0xf08c76, day: 0xbb4227)
    public static let ansiBrightGreen = dynamic(night: 0xa9d684, day: 0x437f2b)
    public static let ansiBrightYellow = dynamic(night: 0xf4cb78, day: 0x8f5f08)
    public static let ansiBrightBlue = dynamic(night: 0x9cc2ec, day: 0x2f72b3)
    public static let ansiBrightMagenta = dynamic(night: 0xddb4e6, day: 0xa052ae)
    public static let ansiBrightCyan = dynamic(night: 0x95d8cc, day: 0x22766d)
    public static let ansiBrightWhite = dynamic(night: 0xf4eee4, day: 0xfcfbf8)

    // MARK: Spacing and radius, in points

    public static let spacing: [String: CGFloat] = [
        "space-1": 4.0,
        "space-2": 8.0,
        "space-3": 12.0,
        "space-4": 16.0,
        "space-6": 24.0,
        "space-8": 32.0,
    ]
    public static let space1: CGFloat = 4.0
    public static let space2: CGFloat = 8.0
    public static let space3: CGFloat = 12.0
    public static let space4: CGFloat = 16.0
    public static let space6: CGFloat = 24.0
    public static let space8: CGFloat = 32.0

    public static let radii: [String: CGFloat] = [
        "radius-xs": 3.0,
        "radius-sm": 6.0,
        "radius-md": 10.0,
        "radius-lg": 14.0,
        "radius-pill": 999.0,
    ]
    public static let radiusXs: CGFloat = 3.0
    public static let radiusSm: CGFloat = 6.0
    public static let radiusMd: CGFloat = 10.0
    public static let radiusLg: CGFloat = 14.0
    public static let radiusPill: CGFloat = 999.0

    // MARK: Motion

    public static let durations: [String: TimeInterval] = [
        "duration-fast": 0.12,
        "duration-base": 0.2,
        "duration-slow": 0.32,
        "duration-halo": 1.6,
    ]
    public static let durationFast: TimeInterval = 0.12
    public static let durationBase: TimeInterval = 0.2
    public static let durationSlow: TimeInterval = 0.32
    public static let durationHalo: TimeInterval = 1.6

    /// A cubic Bezier easing: the two control points.
    public struct Easing: Sendable, Equatable {
        public let x1: Float, y1: Float, x2: Float, y2: Float
    }
    public static let easings: [String: Easing] = [
        "ease-settle": Easing(x1: 0.2, y1: 0.8, x2: 0.2, y2: 1.0),
        "ease-lift": Easing(x1: 0.4, y1: 0.0, x2: 1.0, y2: 1.0),
    ]
    public static let easeSettle = easings["ease-settle"]!
    public static let easeLift = easings["ease-lift"]!

    // MARK: Type

    public struct TypeStyle: Sendable, Equatable {
        public let name: String
        /// "ui", "display", or "mono".
        public let family: String
        public let size: CGFloat
        public let lineHeight: CGFloat
        public let weight: Int
        /// Tracking in em.
        public let tracking: CGFloat
    }
    public static let typeStyles: [TypeStyle] = [
        TypeStyle(name: "window-title", family: "ui", size: 13.0, lineHeight: 16.0, weight: 600, tracking: 0.0),
        TypeStyle(name: "row", family: "ui", size: 13.0, lineHeight: 18.0, weight: 500, tracking: 0.0),
        TypeStyle(name: "body", family: "ui", size: 13.0, lineHeight: 19.0, weight: 400, tracking: 0.0),
        TypeStyle(name: "caption", family: "ui", size: 11.0, lineHeight: 14.0, weight: 500, tracking: 0.0),
        TypeStyle(name: "label", family: "ui", size: 10.5, lineHeight: 14.0, weight: 650, tracking: 0.08),
        TypeStyle(name: "plot-name", family: "ui", size: 20.0, lineHeight: 24.0, weight: 650, tracking: -0.01),
        TypeStyle(name: "brief", family: "ui", size: 14.0, lineHeight: 21.0, weight: 400, tracking: 0.0),
        TypeStyle(name: "wordmark", family: "display", size: 44.0, lineHeight: 48.0, weight: 500, tracking: -0.02),
        TypeStyle(name: "empty-title", family: "display", size: 18.0, lineHeight: 24.0, weight: 500, tracking: 0.0),
        TypeStyle(name: "term", family: "mono", size: 13.0, lineHeight: 17.0, weight: 400, tracking: 0.0),
        TypeStyle(name: "code", family: "mono", size: 12.0, lineHeight: 17.0, weight: 400, tracking: 0.0),
    ]
    public static let windowTitleStyle = typeStyles.first { $0.name == "window-title" }!
    public static let rowStyle = typeStyles.first { $0.name == "row" }!
    public static let bodyStyle = typeStyles.first { $0.name == "body" }!
    public static let captionStyle = typeStyles.first { $0.name == "caption" }!
    public static let labelStyle = typeStyles.first { $0.name == "label" }!
    public static let plotNameStyle = typeStyles.first { $0.name == "plot-name" }!
    public static let briefStyle = typeStyles.first { $0.name == "brief" }!
    public static let wordmarkStyle = typeStyles.first { $0.name == "wordmark" }!
    public static let emptyTitleStyle = typeStyles.first { $0.name == "empty-title" }!
    public static let termStyle = typeStyles.first { $0.name == "term" }!
    public static let codeStyle = typeStyles.first { $0.name == "code" }!
}
