#!/usr/bin/env python3
"""Generates the Swift theme and the Ghostty themes from docs/design/tokens.json.

Writes:
  app/Sources/LoamKit/Theme/LoamTheme.swift
  app/Resources/ghostty-themes/loam-night
  app/Resources/ghostty-themes/loam-day

Run it after any change to tokens.json. LoamThemeTests fails when the outputs
and the JSON disagree. `--check` writes nothing and exits 1 if a file is stale.
"""
import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
tokens = json.loads((root / "docs/design/tokens.json").read_text())


def camel(name: str) -> str:
    head, *rest = name.split("-")
    return head + "".join(part.capitalize() for part in rest)


def hexint(value: str) -> str:
    assert re.fullmatch(r"#[0-9a-f]{6}", value), value
    return "0x" + value[1:]


def px(value: str) -> str:
    assert value.endswith("px"), value
    return value[:-2]


def ms(value: str) -> str:
    assert value.endswith("ms"), value
    return str(int(value[:-2]) / 1000)


def number(text: str) -> str:
    return text if "." in text else text + ".0"


colors = tokens["color"]["tokens"]
out = []
w = out.append
w("// Generated by scripts/gen-loam-theme.py from docs/design/tokens.json. Do not edit.")
w("import AppKit")
w("")
w("/// The Loam design tokens (docs/design). Night is the default theme. Day is the light one.")
w("public enum LoamTheme {")
w("    public struct ColorToken: Sendable, Equatable {")
w("        public let name: String")
w("        public let night: UInt32")
w("        public let day: UInt32")
w("    }")
w("")
w("    /// A color that follows the appearance: Night for dark, Day for light.")
w("    public static func dynamic(night: UInt32, day: UInt32) -> NSColor {")
w("        NSColor(name: nil) { appearance in")
w("            let dark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua")
w("            return srgb(dark ? night : day)")
w("        }")
w("    }")
w("")
w("    public static func srgb(_ hex: UInt32) -> NSColor {")
w("        NSColor(srgbRed: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255,")
w("                blue: CGFloat(hex & 0xFF) / 255, alpha: 1)")
w("    }")
w("")
w("    // MARK: Color")
w("")
w("    public static let colorTokens: [ColorToken] = [")
for t in colors:
    w(f'        ColorToken(name: "{t["name"]}", night: {hexint(t["value"]["night"])}, day: {hexint(t["value"]["day"])}),')
w("    ]")
w("")
# These colors follow the terminal theme (tickets 68 and 70, ChromePalette.swift): the surfaces, the
# ink, and the text-bearing state hues. The washes, edge, and focus stay fixed.
surfaces = {"bedrock", "horizon-o", "horizon-a", "horizon-b", "rule", "frame",
            "ink", "ink-muted", "ink-faint", "moss", "needs-you", "done-unread", "rust"}
for t in colors:
    night, day = hexint(t["value"]["night"]), hexint(t["value"]["day"])
    if t["name"] in surfaces:
        w(f'    public static let {camel(t["name"])} = surface("{t["name"]}", night: {night}, day: {day})')
    else:
        w(f'    public static let {camel(t["name"])} = dynamic(night: {night}, day: {day})')
w("")
w("    // MARK: Spacing and radius, in points")
w("")
w("    public static let spacing: [String: CGFloat] = [")
for t in tokens["spacing"]["tokens"]:
    w(f'        "{t["name"]}": {number(px(t["value"]))},')
w("    ]")
for t in tokens["spacing"]["tokens"]:
    w(f'    public static let {camel(t["name"])}: CGFloat = {number(px(t["value"]))}')
w("")
w("    public static let radii: [String: CGFloat] = [")
for t in tokens["radius"]["tokens"]:
    w(f'        "{t["name"]}": {number(px(t["value"]))},')
w("    ]")
for t in tokens["radius"]["tokens"]:
    w(f'    public static let {camel(t["name"])}: CGFloat = {number(px(t["value"]))}')
w("")
w("    // MARK: Motion")
w("")
w("    public static let durations: [String: TimeInterval] = [")
for t in tokens["duration"]["tokens"]:
    w(f'        "{t["name"]}": {ms(t["value"])},')
w("    ]")
for t in tokens["duration"]["tokens"]:
    w(f'    public static let {camel(t["name"])}: TimeInterval = {ms(t["value"])}')
w("")
w("    /// A cubic Bezier easing: the two control points.")
w("    public struct Easing: Sendable, Equatable {")
w("        public let x1: Float, y1: Float, x2: Float, y2: Float")
w("    }")
w("    public static let easings: [String: Easing] = [")
for t in tokens["easing"]["tokens"]:
    m = re.fullmatch(r"cubic-bezier\(([^,]+),([^,]+),([^,]+),([^)]+)\)", t["value"])
    assert m, t["value"]
    a = [number(x.strip()) for x in m.groups()]
    w(f'        "{t["name"]}": Easing(x1: {a[0]}, y1: {a[1]}, x2: {a[2]}, y2: {a[3]}),')
w("    ]")
for t in tokens["easing"]["tokens"]:
    w(f'    public static let {camel(t["name"])} = easings["{t["name"]}"]!')
w("")
w("    // MARK: Type")
w("")
w("    public struct TypeStyle: Sendable, Equatable {")
w("        public let name: String")
w('        /// "ui", "display", or "mono".')
w("        public let family: String")
w("        public let size: CGFloat")
w("        public let lineHeight: CGFloat")
w("        public let weight: Int")
w("        /// Tracking in em.")
w("        public let tracking: CGFloat")
w("    }")
w("    public static let typeStyles: [TypeStyle] = [")
styles = []
for g in tokens["type"]["groups"]:
    for s in g["styles"]:
        tr = s.get("letterSpacing", "0em")
        assert tr.endswith("em")
        styles.append(s)
        w(f'        TypeStyle(name: "{s["name"]}", family: "{g["family"]}", size: {number(px(s["fontSize"]))}, '
          f'lineHeight: {number(px(s["lineHeight"]))}, weight: {s["fontWeight"]}, tracking: {number(tr[:-2])}),')
w("    ]")
for s in styles:
    w(f'    public static let {camel(s["name"])}Style = typeStyles.first {{ $0.name == "{s["name"]}" }}!')
w("}")
swift = "\n".join(out) + "\n"


def theme(mode: str) -> str:
    c = {t["name"]: t["value"][mode] for t in colors}
    lines = [f"# Loam {mode.capitalize()}. Generated by scripts/gen-loam-theme.py from docs/design/tokens.json."]
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    for i, n in enumerate(names):
        lines.append(f"palette = {i}={c['ansi-' + n]}")
    for i, n in enumerate(names):
        lines.append(f"palette = {i + 8}={c['ansi-bright-' + n]}")
    lines += [
        f"background = {c['bedrock']}",
        f"foreground = {c['ink']}",
        f"cursor-color = {c['cursor']}",
        f"selection-background = {c['selection']}",
        f"selection-foreground = {c['ink']}",
    ]
    return "\n".join(lines) + "\n"


files = {
    root / "app/Sources/LoamKit/Theme/LoamTheme.swift": swift,
    root / "app/Resources/ghostty-themes/loam-night": theme("night"),
    root / "app/Resources/ghostty-themes/loam-day": theme("day"),
}
stale = False
for path, text in files.items():
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != text:
            print(f"stale: {path.relative_to(root)}")
            stale = True
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
sys.exit(1 if stale else 0)
